import argparse
import os
import subprocess
import sys


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train YOLO on labels generated by s3_p1_prepare_yolo_label.py.")
    parser.add_argument(
        "--dataset_path",
        default=None,
        help="Dataset root containing yolo11/train_obj_s. Not needed when --data_path is provided.",
    )
    parser.add_argument(
        "--data_path",
        default=None,
        help="Explicit YOLO data yaml path. Defaults to <dataset_path>/yolo11/train_obj_s/yolo_configs/data_objs.yaml.",
    )
    parser.add_argument("--gpu_num", type=int, default=1)
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--batch", type=int, default=None, help="Defaults to 12 * gpu_num.")
    parser.add_argument("--task", choices=["detection", "segmentation"], default="detection")
    parser.add_argument(
        "--pretrained_weights",
        default=None,
        help="YOLO pretrained weights name or local .pt path. Defaults to yolo11x.pt for detection.",
    )
    parser.add_argument("--amp", action="store_true", help="Enable Ultralytics AMP training checks.")
    parser.add_argument("--multi_scale", action="store_true", help="Enable Ultralytics multi-scale training.")
    parser.add_argument(
        "--skip_if_exists",
        action="store_true",
        help="Skip training if the final exported YOLO model already exists.",
    )
    return parser.parse_args()


def resolve_data_path(args: argparse.Namespace) -> str:
    if args.data_path:
        return os.path.abspath(args.data_path)
    if not args.dataset_path:
        raise ValueError("Pass either --dataset_path or --data_path.")
    return os.path.abspath(
        os.path.join(args.dataset_path, "yolo11", "train_obj_s", "yolo_configs", "data_objs.yaml")
    )


def final_model_path(data_path: str, task: str) -> str:
    train_root = os.path.dirname(os.path.dirname(data_path))
    model_name = f"yolo11-{task}-obj_s.pt"
    return os.path.join(train_root, task, "obj_s", model_name)


def main() -> None:
    args = parse_args()
    data_path = resolve_data_path(args)
    if not os.path.exists(data_path):
        raise FileNotFoundError(f"YOLO data yaml not found: {data_path}")

    model_path = final_model_path(data_path, args.task)
    if args.skip_if_exists and os.path.exists(model_path):
        print(f"[INFO] YOLO model already exists, skipping: {model_path}")
        return

    batch = args.batch if args.batch is not None else 12 * int(args.gpu_num)
    train_script = os.path.join(os.path.dirname(os.path.abspath(__file__)), "yolo_train", "train.py")
    cmd = [
        sys.executable,
        train_script,
        "--data_path",
        data_path,
        "--epochs",
        str(args.epochs),
        "--imgsz",
        str(args.imgsz),
        "--batch",
        str(batch),
        "--gpu_num",
        str(args.gpu_num),
        "--task",
        args.task,
    ]
    if args.pretrained_weights:
        cmd.extend(["--pretrained_weights", args.pretrained_weights])
    if args.amp:
        cmd.append("--amp")
    if args.multi_scale:
        cmd.append("--multi_scale")
    print("[INFO] Running:", " ".join(cmd))
    subprocess.run(cmd, check=True)
    print(f"[INFO] Expected exported YOLO model: {model_path}")


if __name__ == "__main__":
    main()
